export const data = JSON.parse("{\"key\":\"v-b34b3d88\",\"path\":\"/blog/notes-class5.html\",\"title\":\"05-课堂笔记\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"05-课堂笔记\",\"date\":\"2023-01-27T18:07:42.000Z\",\"author\":\"TCreograph\",\"isOriginal\":true,\"category\":[\"blog\"],\"tag\":[\"blog\"],\"icon\":\"vuejs2\",\"sticky\":false,\"star\":false,\"article\":true,\"timeline\":true,\"image\":false,\"navbar\":true,\"sidebarIcon\":true,\"headerDepth\":5,\"comment\":true,\"lastUpdated\":true,\"editLink\":false,\"backToTop\":true,\"toc\":true,\"description\":\"第五课 --创建搜索功能（VSCode&gt;&gt;&gt;config.ts)： image-20230127174602679 image-20230127174848413 --创建菜单栏 (VSCode&gt;&gt;&gt;navbar.ts) image-20230127180423455\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://tcreograph.com/blog/notes-class5.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"TCreograph's Blog\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"05-课堂笔记\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"第五课 --创建搜索功能（VSCode&gt;&gt;&gt;config.ts)： image-20230127174602679 image-20230127174848413 --创建菜单栏 (VSCode&gt;&gt;&gt;navbar.ts) image-20230127180423455\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://tcreograph.com/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"05-课堂笔记\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"TCreograph\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"blog\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-01-27T18:07:42.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"05-课堂笔记\\\",\\\"image\\\":[\\\"https://tcreograph.com/\\\"],\\\"datePublished\\\":\\\"2023-01-27T18:07:42.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"TCreograph\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"第五课\",\"slug\":\"第五课\",\"link\":\"#第五课\",\"children\":[]}],\"readingTime\":{\"minutes\":0.32,\"words\":95},\"filePathRelative\":\"blog/notes-class5.md\",\"localizedDate\":\"2023年1月28日\",\"excerpt\":\"<h2> 第五课</h2>\\n<h4> --创建搜索功能（VSCode&gt;&gt;&gt;config.ts)：</h4>\\n<figure><figcaption>image-20230127174602679</figcaption></figure>\\n<figure><figcaption>image-20230127174848413</figcaption></figure>\\n<h4> --创建菜单栏 (VSCode&gt;&gt;&gt;navbar.ts)</h4>\\n<figure><figcaption>image-20230127180423455</figcaption></figure>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
