import { navbar } from "vuepress-theme-hope";

export const zhNavbar = navbar([
    // "/",
    {
        text:"主页",
        icon:"home",
        link:"/"
    },
    {
        text:"日记",
        icon:"creative",
        link:"#"
    },
    {
        text:"游戏攻略",
        icon:"read",
        children:[
            {
                text:"Genshin Impact (原神)",
                icon:"context",
                link:"#"
            },
            {
                text:"Minecraft (我的世界)",
                icon:"context",
                link:"#"
            },
            {
                text:"Phigros",
                icon:"context",
                link:"#"
            },

        ]
    },
    {
        text:"编程",
        icon:"share",
        children:[
            {
                text:"05-课堂笔记",
                icon:"context",
                link:"/blog/notes-class5"
            },
            {
                text:"06-课堂笔记",
                icon:"context",
                link:"/blog/notes-class6"
            },
            {
                text:"07-课堂笔记",
                icon:"context",
                link:"/blog/notes-class7"
            },
            {
                text:"08-课堂笔记",
                icon:"context",
                link:"/blog/notes-class8"
            },
            {
                text:"09-课堂笔记",
                icon:"context",
                link:"/blog/notes-class9"
            },
            {
                text:"10-课堂笔记",
                icon:"context",
                link:"/blog/notes-class10"
            },
            {
                text:"11-课堂笔记",
                icon:"context",
                link:"/blog/notes-class11"
            },
            {
                text:"12-课堂笔记",
                icon:"context",
                link:"/blog/notes-class12"
            },
            {
                text:"13-课堂笔记",
                icon:"context",
                link:"/blog/notes-class13"
            },
            {
                text:"14-课堂笔记",
                icon:"context",
                link:"/blog/notes-class14"
            },
            {
                text:"15-课堂笔记",
                icon:"context",
                link:"/blog/notes-class15"
            },
            {
                text:"16-课堂笔记",
                icon:"context",
                link:"/blog/notes-class16"
            },
            {
                text:"19-课堂笔记 (不要找了,没有17和18)",
                icon:"context",
                link:"/blog/notes-class19"
            },
            {
                text:"20-课堂笔记 (不要找了,没有17和18)",
                icon:"context",
                link:"/blog/notes-class20"
            },
        ]
    },
]);
