export const data = JSON.parse("{\"key\":\"v-8daa1a0e\",\"path\":\"/\",\"title\":\"Blog Home\",\"lang\":\"zh-CN\",\"frontmatter\":{\"home\":true,\"bgImage\":\"/background2.png\",\"layout\":\"BlogHome\",\"icon\":\"home\",\"title\":\"Blog Home\",\"heroImage\":\"/TCreograph2.png\",\"heroText\":\"TCreograph\",\"tagline\":\"二次元爱好者——主推MC，Phigros，原神\",\"heroFullScreen\":true,\"projects\":[{\"icon\":\"project\",\"name\":\"project name\",\"desc\":\"project detailed description\",\"link\":\"https://your.project.link\"},{\"icon\":\"link\",\"name\":\"link name\",\"desc\":\"link detailed description\",\"link\":\"https://link.address\"},{\"icon\":\"book\",\"name\":\"book name\",\"desc\":\"Detailed description of the book\",\"link\":\"https://link.to.your.book\"},{\"icon\":\"article\",\"name\":\"article name\",\"desc\":\"Detailed description of the article\",\"link\":\"https://link.to.your.article\"},{\"icon\":\"friend\",\"name\":\"friend name\",\"desc\":\"Detailed description of friend\",\"link\":\"https://link.to.your.friend\"},{\"icon\":\"/logo.svg\",\"name\":\"custom item\",\"desc\":\"Detailed description of this custom item\",\"link\":\"https://link.to.your.friend\"}],\"footer\":\"customize your footer text\",\"description\":\"This is a blog home page demo. To use this layout, you should set both layout: BlogHome and home: true in the page front matter. For related configuration docs, please see blog homepage.\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://tcreograph.com/\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"TCreograph's Blog\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Blog Home\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"This is a blog home page demo. To use this layout, you should set both layout: BlogHome and home: true in the page front matter. For related configuration docs, please see blog homepage.\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"website\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}]]},\"headers\":[],\"readingTime\":{\"minutes\":0.52,\"words\":156},\"filePathRelative\":\"README.md\",\"excerpt\":\"<p>This is a blog home page demo.</p>\\n<p>To use this layout, you should set both <code>layout: BlogHome</code> and <code>home: true</code> in the page front matter.</p>\\n<p>For related configuration docs, please see <a href=\\\"https://theme-hope.vuejs.vuepress/guide/blog/home/\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">blog homepage</a>.</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
