export const themeData = JSON.parse("{\"encrypt\":{\"config\":{\"/demo/encrypt.html\":[\"$2a$10$Cv9dVJRvQA91xc3s7xuAveXTeWK/3pIJwnlyimNni0Qo5TlPCrnSK\"],\"/zh/demo/encrypt.html\":[\"$2a$10$PNFD822zqJ1A8jNgkbyRMOD.Fqj7MGSpaguM6lT2GTwsoEOhPAY42\"]}},\"blog\":{\"medias\":{\"GitHub\":\"https://github.com/TCreograph\",\"MrHope\":\"https://mrhope.site\"}},\"locales\":{\"/\":{\"lang\":\"zh-CN\",\"navbarLocales\":{\"langName\":\"简体中文\",\"selectLangAriaLabel\":\"选择语言\"},\"metaLocales\":{\"author\":\"作者\",\"date\":\"写作日期\",\"origin\":\"原创\",\"views\":\"访问量\",\"category\":\"分类\",\"tag\":\"标签\",\"readingTime\":\"阅读时间\",\"words\":\"字数\",\"toc\":\"此页内容\",\"prev\":\"上一页\",\"next\":\"下一页\",\"lastUpdated\":\"上次编辑于\",\"contributors\":\"贡献者\",\"editLink\":\"在 GitHub 上编辑此页\"},\"blogLocales\":{\"article\":\"文章\",\"articleList\":\"文章列表\",\"category\":\"分类\",\"tag\":\"标签\",\"timeline\":\"时间轴\",\"timelineTitle\":\"昨日不在\",\"all\":\"全部\",\"intro\":\"个人介绍\",\"star\":\"收藏\"},\"paginationLocales\":{\"prev\":\"上一页\",\"next\":\"下一页\",\"navigate\":\"跳转到\",\"action\":\"前往\",\"errorText\":\"请输入 1 到 $page 之前的页码！\"},\"outlookLocales\":{\"themeColor\":\"主题色\",\"darkmode\":\"外观\",\"fullscreen\":\"全屏\"},\"encryptLocales\":{\"iconLabel\":\"文章已加密\",\"placeholder\":\"输入密码\",\"remember\":\"记住密码\",\"errorHint\":\"请输入正确的密码\"},\"routeLocales\":{\"skipToContent\":\"跳至主要內容\",\"notFoundTitle\":\"页面不存在\",\"notFoundMsg\":[\"这里什么也没有\",\"我们是怎么来到这儿的？\",\"这 是 四 零 四 !\",\"看起来你访问了一个失效的链接\"],\"back\":\"返回上一页\",\"home\":\"带我回家\",\"openInNewWindow\":\"Open in new window\"},\"author\":{\"name\":\"TCreograph\",\"url\":\"https://tcreograph.com/\"},\"logo\":\"/TCreograph2.png\",\"repo\":\"TCreograph/TCreograph.github.io\",\"docsDir\":\"src\",\"pageInfo\":[\"Author\",\"Original\",\"Date\",\"Category\",\"Tag\",\"ReadingTime\",\"Word\",\"PageView\"],\"navbar\":[{\"text\":\"主页\",\"icon\":\"home\",\"link\":\"/\"},{\"text\":\"日记\",\"icon\":\"creative\",\"link\":\"#\"},{\"text\":\"游戏攻略\",\"icon\":\"read\",\"children\":[{\"text\":\"原神\",\"icon\":\"context\",\"link\":\"#\"},{\"text\":\"MC\",\"icon\":\"context\",\"link\":\"#\"},{\"text\":\"Phigros\",\"icon\":\"context\",\"link\":\"#\"}]},{\"text\":\"编程\",\"icon\":\"share\",\"children\":[{\"text\":\"05-课堂笔记\",\"icon\":\"context\",\"link\":\"/blog/notes-class5\"},{\"text\":\"06-课堂笔记\",\"icon\":\"context\",\"link\":\"/blog/notes-class6\"}]}],\"sidebar\":{},\"footer\":\"默认页脚\",\"displayFooter\":true,\"blog\":{\"name\":\"TCreograph\",\"avatar\":\"/TCreograph2.png\",\"description\":\"纳西妲教教主 ~ 种门最忠诚的信徒\",\"intro\":\"/about.md\"}}}}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateThemeData) {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ themeData }) => {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  })
}
